name: Git Sync

on:
  push:
    branches:
      - main
      - master
      - development

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          # source_repo: "alphasistemas/auth"
          # get personal access token
          personal_access_token: ${{ secrets.GIT_SYNC }}
          #insert pat into source_repo
          source_repo: "https://levyam:personal_access_token@github.com/levyam/crud_nestjs.git"
          source_branch: "refs/remotes/source/*"
          destination_repo: "levyam/clone"
          destination_branch: "refs/heads/*"
          # ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # optional
          # source_ssh_private_key: ${{ secrets.SOURCE_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
          # destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
